// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnr3My8EM8Q66ryHrS97-ZKNQdqNw8TOQ',
    appId: '1:757116387137:web:4a4238778889f625666bc0',
    messagingSenderId: '757116387137',
    projectId: 'recipe-book-c3726',
    authDomain: 'recipe-book-c3726.firebaseapp.com',
    storageBucket: 'recipe-book-c3726.firebasestorage.app',
    measurementId: 'G-3CPY3X6MS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV5cyUSFiNtEENXWuEjAEvaiwnzqm_I1M',
    appId: '1:757116387137:android:5894b91ee4cddedf666bc0',
    messagingSenderId: '757116387137',
    projectId: 'recipe-book-c3726',
    storageBucket: 'recipe-book-c3726.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMmYgYDkswLKLDcNIXBdV5a6R5NcN1qDs',
    appId: '1:757116387137:ios:8e82a1b8e1ce44c3666bc0',
    messagingSenderId: '757116387137',
    projectId: 'recipe-book-c3726',
    storageBucket: 'recipe-book-c3726.firebasestorage.app',
    iosBundleId: 'com.example.recipeBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMmYgYDkswLKLDcNIXBdV5a6R5NcN1qDs',
    appId: '1:757116387137:ios:8e82a1b8e1ce44c3666bc0',
    messagingSenderId: '757116387137',
    projectId: 'recipe-book-c3726',
    storageBucket: 'recipe-book-c3726.firebasestorage.app',
    iosBundleId: 'com.example.recipeBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnr3My8EM8Q66ryHrS97-ZKNQdqNw8TOQ',
    appId: '1:757116387137:web:d886a145493cddad666bc0',
    messagingSenderId: '757116387137',
    projectId: 'recipe-book-c3726',
    authDomain: 'recipe-book-c3726.firebaseapp.com',
    storageBucket: 'recipe-book-c3726.firebasestorage.app',
    measurementId: 'G-YY9V3E7CWH',
  );
}
